# Generated by Django 4.2.2 on 2023-06-21 22:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CambioEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHoraInicio', models.DateTimeField(default=datetime.datetime.now)),
                ('fechaHoraFin', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'cambio_estado',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(default='', max_length=9, unique=True)),
                ('nombre', models.CharField(default='', max_length=255)),
                ('nroCelular', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='iniciada', max_length=100)),
            ],
            options={
                'db_table': 'estado',
            },
        ),
        migrations.CreateModel(
            name='InformacionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datoAValidar', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'informacion_cliente',
            },
        ),
        migrations.CreateModel(
            name='OpcionValidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correcta', models.BooleanField(default=False)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SubOpcionLlamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=255)),
                ('nroOrden', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'sub_opcion_llamada',
            },
        ),
        migrations.CreateModel(
            name='TipoInformacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'tipo_informacion',
            },
        ),
        migrations.CreateModel(
            name='Validacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audioMensajeValidacion', models.CharField(max_length=255, null=True)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('opcionesValidacion', models.ManyToManyField(to='app_operador.opcionvalidacion')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_operador.tipoinformacion')),
            ],
            options={
                'db_table': 'validacion',
            },
        ),
        migrations.CreateModel(
            name='OpcionLlamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audioMensajeSubopciones', models.CharField(max_length=255, null=True)),
                ('mensajeSubopciones', models.TextField(null=True)),
                ('nroOrden', models.IntegerField(null=True)),
                ('nombre', models.CharField(default='', max_length=255)),
                ('subOpciones', models.ManyToManyField(to='app_operador.subopcionllamada')),
                ('validaciones', models.ManyToManyField(to='app_operador.validacion')),
            ],
            options={
                'db_table': 'opcion_llamada',
            },
        ),
        migrations.CreateModel(
            name='Llamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcionOperador', models.CharField(max_length=255, null=True)),
                ('detalleAccionRequerida', models.TextField(null=True)),
                ('duracion', models.IntegerField(default=0)),
                ('encuestaEnviada', models.BooleanField(null=True)),
                ('observacionAuditor', models.TextField(null=True)),
                ('cambiosEstado', models.ManyToManyField(to='app_operador.cambioestado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_operador.cliente')),
                ('estadoActual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_operador.estado')),
                ('subOpcion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_operador.subopcionllamada')),
            ],
            options={
                'db_table': 'llamada',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='info',
            field=models.ManyToManyField(to='app_operador.informacioncliente'),
        ),
        migrations.CreateModel(
            name='CategoriaLlamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audioMensajeSubopciones', models.CharField(default='', max_length=255)),
                ('mensajeSubopciones', models.TextField(null=True)),
                ('nroOrden', models.IntegerField(default=0)),
                ('nombre', models.CharField(default='', max_length=255)),
                ('opciones', models.ManyToManyField(to='app_operador.opcionllamada')),
            ],
            options={
                'db_table': 'categoria_llamada',
            },
        ),
        migrations.AddField(
            model_name='cambioestado',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_operador.estado'),
        ),
    ]
