from .estado import Estado
from .cambio_estado import CambioEstado
from .categoria_llamada import CategoriaLlamada
from .cliente import Cliente
from .informacion_cliente import InformacionCliente
from .llamada import Llamada
from .opcion_llamada import OpcionLlamada
from .sub_opcion_llamada import SubOpcionLlamada
from .validacion import Validacion
from .tipo_informacion import TipoInformacion
from .opcion_validacion import OpcionValidacion
